[build]
publish = "."
functions = "netlify/functions"

[[redirects]]
from = "/api/pi/approve"
to = "/.netlify/functions/pi_approve"
status = 200
force = true

[[redirects]]
from = "/api/pi/complete"
to = "/.netlify/functions/pi_complete"
status = 200
force = true
[[headers]]
  for = "/.well-known/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "text/plain; charset=utf-8"